name: Update Prices

on:
  schedule:
    - cron: '0 */6 * * *'  # toutes les 6 heures
  workflow_dispatch:       # permet aussi de le lancer manuellement

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip3 install requests

    - name: Run update_prices.py
      run: python3 update_prices.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PRICE_UPDATES_TOKEN }}
      run: |
        git config user.name "Arash Nemat Zadeh"
        git config user.email "arashnm80@gmail.com"
        git add prices.json
        git commit -m "Update prices.json [automated]" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD
